"use client";

import { useState } from "react";
import { useSession } from "next-auth/react";
import { Bookmark, Share2, Download } from "lucide-react";

type Level = "Beginner" | "Intermediate" | "Advanced";

type CourseModule = {
  title: string;
  description: string;
  duration: string;
};

type RoadmapStep = {
  step: number;
  title: string;
  action: string;
};

type YoutubeLink = {
  title: string;
  url: string;
};

type RecommendedCourse = {
  title: string;
  provider: string;
  url: string;
};

export default function CourseGenerator() {
  const { data: session } = useSession();
  const [name, setName] = useState("");
  const [focus, setFocus] = useState("AI & Machine Learning");
  const [level, setLevel] = useState<Level>("Beginner");
  const [goals, setGoals] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [course, setCourse] = useState<CourseModule[] | null>(null);
  const [roadmap, setRoadmap] = useState<RoadmapStep[] | null>(null);
  const [youtubeLinks, setYoutubeLinks] = useState<YoutubeLink[] | null>(null);
  const [recommendedCourses, setRecommendedCourses] = useState<RecommendedCourse[] | null>(null);
  const [error, setError] = useState("");
  const [courseId, setCourseId] = useState<string | null>(null);
  const [isSaved, setIsSaved] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError("");

    try {
      const response = await fetch("/api/generate-course", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name,
          focus,
          level,
          goals,
        }),
      });

      if (!response.ok) {
        throw new Error("Failed to generate course");
      }

      const data = await response.json();

      setCourse(data.course);
      setRoadmap(data.roadmap);
      setYoutubeLinks(data.youtubeLinks);
      setRecommendedCourses(data.recommendedCourses);
      setCourseId(data.courseId);
      setIsSaved(false); // Reset save state for new course
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate course");
    } finally {
      setIsLoading(false);
    }
  };

  const handleSaveCourse = async () => {
    if (!courseId || !session) return;

    setIsSaving(true);
    try {
      const response = await fetch(`/api/courses/${courseId}/save`, {
        method: "POST",
      });

      if (!response.ok) {
        throw new Error("Failed to save course");
      }

      setIsSaved(!isSaved);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to save course");
    } finally {
      setIsSaving(false);
    }
  };

  const handleShareCourse = () => {
    if (navigator.share && course) {
      navigator.share({
        title: `My ${focus} Learning Path`,
        text: `Check out my personalized ${focus} course generated by AI CourseCrafter!`,
        url: window.location.href,
      });
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(window.location.href);
      // You could add a toast notification here
    }
  };

  const handleExportCourse = () => {
    if (!course || !roadmap) return;

    const courseData = {
      title: `Personalized ${focus} Course`,
      level,
      goals,
      generatedAt: new Date().toISOString(),
      course,
      roadmap,
      youtubeLinks,
      recommendedCourses,
    };

    const dataStr = JSON.stringify(courseData, null, 2);
    const dataUri = 'data:application/json;charset=utf-8,'+ encodeURIComponent(dataStr);

    const exportFileDefaultName = `course-${focus.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.json`;

    const linkElement = document.createElement('a');
    linkElement.setAttribute('href', dataUri);
    linkElement.setAttribute('download', exportFileDefaultName);
    linkElement.click();
  };

  return (
    <section id="course-generator" className="py-20 px-4 sm:px-6 lg:px-8 bg-white dark:bg-gray-950">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-4xl lg:text-6xl font-black mb-4 tracking-tight text-black dark:text-white">Generate Your Learning Path</h2>
          <p className="text-lg text-gray-700 dark:text-gray-300 max-w-2xl mx-auto font-400">
            Enter your interests and goals, then let AI create a full roadmap with trusted resources, YouTube tutorials, and top course picks.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <form onSubmit={handleSubmit} className="space-y-5 bg-white dark:bg-gray-800 p-8 rounded-2xl shadow-lg border border-gray-200 dark:border-gray-700">
            <div>
              <label htmlFor="name" className="block text-sm font-700 text-black dark:text-white mb-2">Your Name</label>
              <input
                id="name"
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Jane Doe"
                className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg shadow-sm focus:border-black dark:focus:border-white focus:ring-2 focus:ring-black dark:focus:ring-white text-black dark:text-white bg-white dark:bg-gray-700 transition-all"
                required
              />
            </div>

            <div>
              <label htmlFor="focus" className="block text-sm font-700 text-black dark:text-white mb-2">Focus Area</label>
              <select
                id="focus"
                value={focus}
                onChange={(e) => setFocus(e.target.value)}
                className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg shadow-sm focus:border-black dark:focus:border-white focus:ring-2 focus:ring-black dark:focus:ring-white text-black dark:text-white bg-white dark:bg-gray-700 transition-all"
              >
                <option>AI & Machine Learning</option>
                <option>Web Development</option>
                <option>Data Science</option>
                <option>Cloud Engineering</option>
                <option>Cybersecurity</option>
                <option>Mobile Development</option>
                <option>DevOps</option>
                <option>Blockchain</option>
                <option>Game Development</option>
              </select>
            </div>

            <div>
              <label htmlFor="level" className="block text-sm font-700 text-black dark:text-white mb-2">Skill Level</label>
              <select
                id="level"
                value={level}
                onChange={(e) => setLevel(e.target.value as Level)}
                className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg shadow-sm focus:border-black dark:focus:border-white focus:ring-2 focus:ring-black dark:focus:ring-white text-black dark:text-white bg-white dark:bg-gray-700 transition-all"
              >
                <option>Beginner</option>
                <option>Intermediate</option>
                <option>Advanced</option>
              </select>
            </div>

            <div>
              <label htmlFor="goals" className="block text-sm font-700 text-black dark:text-white mb-2">Learning Goals</label>
              <textarea
                id="goals"
                value={goals}
                onChange={(e) => setGoals(e.target.value)}
                placeholder="Explain what you want to achieve in 1-2 sentences"
                className="w-full px-4 py-3 h-24 border border-gray-300 dark:border-gray-600 rounded-lg shadow-sm focus:border-black dark:focus:border-white focus:ring-2 focus:ring-black dark:focus:ring-white text-black dark:text-white bg-white dark:bg-gray-700 transition-all resize-none"
                required
              />
            </div>

            <button
              type="submit"
              className="w-full bg-black dark:bg-white text-white dark:text-black px-5 py-3.5 rounded-full font-700 text-base shadow-lg hover:shadow-2xl transition-all duration-300 hover:scale-105"
              disabled={isLoading}
            >
              {isLoading ? "Generating..." : "Generate Course"}
            </button>

            {error && <p className="text-sm text-red-600 font-500">{error}</p>}
          </form>

          <div className="space-y-6">
            <div className="bg-white dark:bg-gray-800 p-6 rounded-2xl border border-gray-200 dark:border-gray-700 shadow-sm">
              <div className="flex justify-between items-center mb-4">
                <h3 className="text-2xl font-700 text-black dark:text-white">Generated Course Outline</h3>
                {course && session && courseId && (
                  <div className="flex gap-2">
                    <button
                      onClick={handleSaveCourse}
                      disabled={isSaving}
                      className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all ${
                        isSaved
                          ? "bg-gray-800 text-white dark:bg-white dark:text-black border border-gray-700 dark:border-gray-300"
                          : "bg-gray-200 text-gray-800 dark:bg-gray-700 dark:text-gray-200 border border-gray-300 dark:border-gray-600 hover:bg-gray-300 dark:hover:bg-gray-600"
                      }`}
                    >
                      <Bookmark size={16} className={isSaved ? "fill-current" : ""} />
                      {isSaving ? "Saving..." : isSaved ? "Saved" : "Save"}
                    </button>
                    <button
                      onClick={handleShareCourse}
                      className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium bg-gray-200 text-gray-800 dark:bg-gray-700 dark:text-gray-200 border border-gray-300 dark:border-gray-600 hover:bg-gray-300 dark:hover:bg-gray-600 transition-all"
                    >
                      <Share2 size={16} />
                      Share
                    </button>
                    <button
                      onClick={handleExportCourse}
                      className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium bg-gray-200 text-gray-800 dark:bg-gray-700 dark:text-gray-200 border border-gray-300 dark:border-gray-600 hover:bg-gray-300 dark:hover:bg-gray-600 transition-all"
                    >
                      <Download size={16} />
                      Export
                    </button>
                  </div>
                )}
              </div>
              {isLoading && <p className="text-gray-600 dark:text-gray-400 font-400">Your personalized path is being created...</p>}
              {!isLoading && !course && <p className="text-gray-600 dark:text-gray-400 font-400">Submit your details to see a custom roadmap.</p>}

              {course && (
                <div className="grid grid-cols-1 gap-4">
                  {course.map((module, index) => (
                    <div key={index} className="card-hover bg-gray-50 dark:bg-gray-700 p-6 rounded-2xl border border-gray-200 dark:border-gray-600 shadow-md hover:shadow-lg transition-all duration-300">
                      <p className="text-xs font-700 text-black dark:text-white mb-2">MODULE {index + 1} • {module.duration}</p>
                      <h4 className="text-lg font-700 text-black dark:text-white mb-2">{module.title}</h4>
                      <p className="text-gray-600 dark:text-gray-300 text-sm font-400">{module.description}</p>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {roadmap && (
              <div className="bg-white dark:bg-gray-800 p-6 rounded-2xl border border-gray-200 dark:border-gray-700 shadow-sm">
                <h3 className="text-2xl font-700 text-black dark:text-white mb-4">Roadmap</h3>
                <ol className="space-y-4 list-decimal list-inside text-gray-600 dark:text-gray-300">
                  {roadmap.map((step) => (
                    <li key={step.step} className="space-y-2">
                      <p className="font-700 text-black dark:text-white">{step.title}</p>
                      <p className="text-sm">{step.action}</p>
                    </li>
                  ))}
                </ol>
              </div>
            )}

            {youtubeLinks && (
              <div className="bg-white dark:bg-gray-800 p-6 rounded-2xl border border-gray-200 dark:border-gray-700 shadow-sm">
                <h3 className="text-2xl font-700 text-black dark:text-white mb-4">Recommended YouTube Resources</h3>
                <ul className="space-y-3 text-gray-600 dark:text-gray-300">
                  {youtubeLinks.map((link) => (
                    <li key={link.url}>
                      <a href={link.url} target="_blank" rel="noreferrer" className="font-600 text-black dark:text-white underline-offset-2 hover:underline">
                        {link.title}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {recommendedCourses && (
              <div className="bg-white dark:bg-gray-800 p-6 rounded-2xl border border-gray-200 dark:border-gray-700 shadow-sm">
                <h3 className="text-2xl font-700 text-black dark:text-white mb-4">Famous Courses Many Learners Follow</h3>
                <div className="grid gap-4">
                  {recommendedCourses.map((courseItem) => (
                    <a
                      key={courseItem.url}
                      href={courseItem.url}
                      target="_blank"
                      rel="noreferrer"
                      className="block rounded-2xl border border-gray-200 dark:border-gray-600 p-4 hover:border-black dark:hover:border-white hover:bg-gray-100 dark:hover:bg-gray-700 transition-all"
                    >
                      <p className="font-700 text-black dark:text-white">{courseItem.title}</p>
                      <p className="text-sm text-gray-600 dark:text-gray-400">{courseItem.provider}</p>
                    </a>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}
